name: Example

on:
  - push
  - workflow_dispatch

jobs:
  if:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Check all modified files
       run: |
         pwd
         ls
         git log|head
